import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  header: {
    paddingTop: 50,
    paddingHorizontal: 25,
    paddingBottom: 25,
    backgroundColor: '#2A5CFF',
    borderBottomLeftRadius: 25,
    borderBottomRightRadius: 25,
    shadowColor: '#2A5CFF',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.1,
    shadowRadius: 20,
    elevation: 10,
  },
  headerTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 25,
  },
  welcomeContainer: {},
  welcomeTitle: {
    fontSize: 26,
    fontWeight: '600',
    color: '#FFFFFF',
    marginBottom: 5,
  },
  welcomeSubtitle: {
    fontSize: 14,
    color: 'rgba(255,255,255,0.9)',
  },
  avatar: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.9)',
    borderRadius: 12,
    paddingHorizontal: 15,
    height: 50,
  },
  searchInput: {
    flex: 1,
    fontSize: 16,
    color: '#1C1F34',
    marginLeft: 10,
  },
  content: {
    paddingHorizontal: 25,
    paddingTop: 25,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#1C1F34',
  },
  seeAll: {
    fontSize: 14,
    color: '#2A5CFF',
    fontWeight: '500',
  },
  categoryGrid: {
    paddingBottom: 10,
  },
  categoryCard: {
    flex: 1,
    margin: 8,
    height: 130,
    borderRadius: 15,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#F0F4FF',
    shadowColor: '#2A5CFF',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 3,
  },
  categoryIconContainer: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#F0F4FF',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
  },
  categoryText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#1C1F34',
  },
  popularServiceCard: {
    height: 180,
    borderRadius: 15,
    backgroundColor: '#F8FAFF',
    flexDirection: 'row',
    overflow: 'hidden',
    marginBottom: 30,
    borderWidth: 1,
    borderColor: '#F0F4FF',
  },
  popularServiceContent: {
    flex: 1,
    padding: 20,
    justifyContent: 'center',
  },
  popularServiceTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#1C1F34',
    marginBottom: 5,
  },
  popularServiceSubtitle: {
    fontSize: 14,
    color: '#8F8F8F',
    marginBottom: 10,
  },
  popularServiceImage: {
    width: 120,
    backgroundColor: '#E6EDFF',
  },
  ratingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
  },
  ratingText: {
    fontSize: 13,
    color: '#8F8F8F',
    marginLeft: 5,
  },
  bookNowButton: {
    backgroundColor: '#2A5CFF',
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 20,
    alignSelf: 'flex-start',
  },
  bookNowText: {
    color: '#FFFFFF',
    fontWeight: '500',
    fontSize: 14,
  },
});